import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react';
import * as Scrivito from 'scrivito';
import styles from '../styles/Home.module.css'

Scrivito.configure({
  tenant: "248dcdc062ec51d2f89f91c23d192898",
  unstable: { assetUrlBase: "http://localhost:8091" },
});

export async function getServerSideProps() {
  const obj = await Scrivito.load(() => Scrivito.Obj.getByPath('/'));
  const objCount = await Scrivito.load(() => Scrivito.Obj.all().count());

  return {
    props: {
      // objId: obj.id(),
      objCount,
    },
  };
}

const Home: NextPage = ({ objId, objCount }) => {
  console.log('>>>>>>>>>>>>>', objCount);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Scrivito.LinkTag to={ new Scrivito.Link({url: 'https://scrivito.com'})}>
          scrivito.com
        </Scrivito.LinkTag>
      </main>
    </div>
  )
}

export default Home
